# Generated by Django 3.2 on 2023-09-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Укажите жанр произведения', max_length=64, verbose_name='Жанр произведения')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Укажите название произведения', max_length=256, verbose_name='Название произведения')),
                ('year', models.IntegerField(help_text='Укажите год выпуска произведения', verbose_name='Год издания')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
            },
        ),
        migrations.CreateModel(
            name='Сategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Укажите тип произведения', max_length=64, verbose_name='Тип произведения')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Title_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.genre', verbose_name='Жанр произведения')),
                ('title_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.title', verbose_name='Название произведения')),
            ],
            options={
                'verbose_name': 'Произведение - Жанр',
                'verbose_name_plural': 'Произведение - Жанр',
            },
        ),
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.сategory', verbose_name='Тип произведения'),
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='titles', through='reviews.Title_genre', to='reviews.Genre', verbose_name='Жанр произведения'),
        ),
    ]
